### ISSUE TITLE
Error while using while using  Kitura v. 20 for onResponseEnd member

### ISSUE THREAD

**Issue by Kam21** [IBM-Swift/Kitura-ResponseTime#1]
Error on  "response.onResponseEnd "  -   **value of type  'RouterResponse' has no member 'onResponseEnd;**

**Function:** 
    public func handle(request: RouterRequest, response: RouterResponse, next: () -> Void) throws {
        startTime = NSDate()

```
    let previousOnResponseEnd = **response.onResponseEnd** ?? nil
    **response.onResponseEnd** = { [unowned self, unowned response] in
```

}

**Comment by ianpartridge** [comment]
I'm sorry we missed this issue. Please reopen if you still need help.
